### ISSUE TITLE
RHEL 9 support

### ISSUE THREAD

**Issue by jcpunk** [treydock/puppet-kdump#16]
From the RHEL9 release notes:

> A new crashkernel.default file for kdump memory allocation
>
> A new implementation of the crashkernel.default file is now available on the RHEL 9 version of kdump.
>
> The crashkernel.default file is shipped with each kernel and it contains the default crash kernel value for the corresponding kernel build. The default value is used by kdump to control the default crash kernel memory value of each kernel. The value forms a good reference for kdump memory reservation. Using this value as the base to estimate the required memory, you can configure the desired crashkernel= value.
>
> As a result, this improves the memory allocation for kdump when a system has less than 4 GB available memory.
>
> Note that the crashkernel=auto option in the boot command line is no longer supported on RHEL 9 and later releases.
>
> For more information, see the /usr/share/doc/kexec-tools/crashkernel-howto.txt file.

Can this module be updated to use the new `crashkernel.default` file?

**Comment by treydock** [comment]
I think this module could manage that. It will be easier once something like Rocky Linux has EL9 builds but I suppose could evaluate using CentOS Stream.  Would be hard to add to this module until the Puppet unit testing supports EL9 as that will be how the unit tests get fact values.
