### ISSUE TITLE
Replace augeasproviders_grub due to deprecation

### ISSUE THREAD

**Issue by rridge532** [treydock/puppet-kdump#19]
`herculesteam-augeasproviders_grub` has been deprecated in favor of `puppet-augeasproviders_grub`. Puppet throws a warning when running `puppet module list` and also fails [S0035 of pe_status_check](https://forge.puppet.com/modules/puppetlabs/pe_status_check/readme#fact-pe_status_check)

**Comment by treydock** [comment]
Solved with #22
